---
title: "GSSTDA Vignette: Gene Structure Survival using Topological Data Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GSSTDA-vignette}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette represents an introduction to the use of the package G-SS-TDA. 

```{r setup}
library(GSSTDA)
```

Loading data:
```{r}
data("full_data")
data("survival_time")
data("survival_event")
data("case_tag")
```


Declare the necessary parameters of the GSSTDA object.
```{r}
# Gene selection information
gen_select_type <- "Top_Bot"
percent_gen_select <- 90 # Percentage of genes to be selected


#Mapper information
num_intervals <- 5
percent_overlap <- 0.4
distance_type <- "euclidean"
clustering_type <- "hierarchical"
num_bins_when_clustering <- 10
linkage_type <- "single"

```

Create the GSSTDA object with full data set, internally pre-process using the DGSA technique, and the mapper information.
```{r}
GSSTDA_obj <- GSSTDA(full_data, survival_time, survival_event, case_tag, gen_select_type, percent_gen_select, num_intervals, percent_overlap, distance_type, clustering_type, num_bins_when_clustering, linkage_type)

```

Obtain information from the mapper object created in the previous step.
```{r}
mapper_infor <- get_information_from_results(GSSTDA_obj[["mapper_obj"]])

print(mapper_infor)
```

Plot the mapper graph.
```{r}
plot_mapper(GSSTDA_obj[["mapper_obj"]])
```
